### ISSUE TITLE
"Save" button in toolbar returns txt file with undefined content

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/ardublockly-1#28]
On https://blockly.sensebox.de/ardublockly/?lang=de&board=sensebox-mcu# the shortcut for saving returns the file download.txt with undefinded data. If you use the context menu to save a file, it seems to work.
Running in Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by mpfeil** [comment]
I suggest to use the following function `saveXmlFile`.
The user can only load `xml` files. So we should change the saving dialog to `xml` also.
