### ISSUE TITLE
Add german translations

### ISSUE THREAD

**Issue by mpfeil** [sensebox/ardublockly-1#5]

**Comment by mpfeil** [comment]
@bgunt in der folgenden Datei https://github.com/sensebox/ardublockly-1/blob/master/ardublockly/msg/de.js kannst du das Frontend übersetzen. Dazu zählen aber später nicht die Übersetzungen der Blöcke!

**Comment by mpfeil** [comment]
Hier noch der Link zur Beschreibung der einzelnen Sprachdateien https://github.com/carlosperate/ardublockly/wiki/Add-New-Language

**Comment by bgunt** [comment]
@mpfeil @robarto @janwirwahn @mariopesch Bitte nochmal korrigieren.
