### ISSUE TITLE
Prevent Filenames longer than 8 characters

### ISSUE THREAD

**Issue by mariopesch** [sensebox/ardublockly-1#77]
The length of the filename in the SD Block must < 8 Characters. Implement a feature to prevent filenames longer than 8 characters.

> FAT file systems have a limitation when it comes to naming conventions. You must use the 8.3 format, so that file names look like “NAME001.EXT”, where “NAME001” is an 8 character or fewer string, and “EXT” is a 3 character extension. People commonly use the extensions .TXT and .LOG. It is possible to have a shorter file name (for example, mydata.txt, or time.log), but you cannot use longer file names. Read more on the 8.3 convention.

**Comment by mpfeil** [comment]
You can use the following regex:
```regex
(^[\w,\s-]{0,8})+\.[A-Za-z]{3}$
```
